"""create farmers and message_logs tables

Revision ID: 54bede500164
Revises: 
Create Date: 2026-09-27 05:07:42.037568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bede500164'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('main_crops', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_index(op.f('ix_farmers_phone_number'), 'farmers', ['phone_number'], unique=True)
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_id'), 'message_logs', ['id'], unique=False)
    op.create_index(op.f('ix_message_logs_phone_number'), 'message_logs', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_logs_phone_number'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_id'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_farmers_phone_number'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
